# Generated by Django 6.0.4 on 2026-05-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
    ]
