# Generated by Django 6.0.4 on 2026-05-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_category_available_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('text', models.CharField(blank=True, max_length=300, verbose_name='Дополнительный текст')),
                ('icon', models.CharField(choices=[('local_shipping', 'Доставка'), ('schedule', 'Время'), ('storefront', 'Самовывоз'), ('payments', 'Оплата'), ('percent', 'Скидка'), ('local_fire_department', 'Горячее предложение')], max_length=100, verbose_name='Иконка')),
                ('type', models.CharField(choices=[('info', 'Информация'), ('promo', 'Акция')], default='info', max_length=10, verbose_name='Тип')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Инфо-блок',
                'verbose_name_plural': 'Инфо-блоки',
                'ordering': ['order'],
            },
        ),
    ]
