# Generated by Django 6.0.4 on 2026-05-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sitesettings_split_working_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=6, verbose_name='Стоимость доставки (BYN)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=40, max_digits=6, verbose_name='Бесплатная доставка от (BYN)'),
        ),
    ]
