# Generated by Django 6.0.4 on 2026-05-15 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_add_delivery_settings_to_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='sushimoby@mail.ru', max_length=254, verbose_name='Email для уведомлений о заказах'),
        ),
    ]
